spring:
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: rule-engine-group
      auto-offset-reset: earliest
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: com.fraud.common.dto
        spring.json.value.default.type: com.fraud.common.dto.TransactionEvent
